### ISSUE TITLE
Inconsistent naming of `IPage` events

### ISSUE THREAD

**Issue by PJBarczyk** [AnnulusGames/NavStack#6]
As stated in **Page Lifecycle** section, the basic `IPage` events are:

- `OnNavigatedFrom` - Called when navigating away **from** the Page.
- `OnNavigatedTo` - Called when navigating **to** the Page.

Despite this, all examples shown in the *README* use them the other way around. Same goes for the `NavigationStackCore` and `NavigationSheetCore` implementations, e.g.:

```csharp
public async UniTask PopAsync(INavigation navigation, NavigationContext context, CancellationToken cancellationToken = default)
{
    // Parts of the code omitted for brevity
    pageStack.TryPop(out var page);
    pageStack.TryPeek(out activePage);

    var task1 = page.OnNavigatedTo(copiedContext, cancellationToken); // Should be OnNavigatedFrom
    var task2 = activePage == null ? UniTask.CompletedTask : activePage.OnNavigatedFrom(copiedContext, cancellationToken); // Should be OnNavigatedTo
}
```

The definitions in **Page Lifecycle** section sound reasonable, so I suppose the other parts of the repository should be updated to match them. If so, I'd be happy to provide a PR with the changes.

**Comment by nuskey8** [comment]
Ah, I seem to have confused these two when implementing it. As you say, the definition of README is correct. I've created a revised PR on my end, so I'll merge it once I'm sure there are no issues.
